apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 12
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
    spec:
      containers:
      - name: api-deployment
        image: docker pull gcr.io/kube-224111/admin:latest
        ports:
        - containerPort: 8080
